buildCommand: |
  pnpm install --frozen-lockfile &&
  pip install -r requirements.txt &&
  pip install psycopg2 &&
  ls &&
  cd api &&
  flask db upgrade &&
  flask seed all &&
  cd .. &&
  pnpm run build

paths:
  - .local/bin:$PATH
