'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import Context from './components/Context/context'
import { usePathname} from 'next/navigation'


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()

  return (
    <Context>
      <html lang='en'>
        <body
          className={`${inter.className} antialiased container-full mx-auto`}
        >
          {!pathname.startsWith('/dashboard') && <Navbar />}
          {children}
        </body>
      </html>
    </Context>
  )
}
