import { Inter } from 'next/font/google'
import Link from 'next/link'
import Button from '../components/Button'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function Layout({
    children,
}: {
    children: React.ReactNode
}) {


    return (

        <div
            className={`${inter.className} antialiased container-full mx-auto flex`}
        >
            <div className="w-64 bg-white shadow-md flex flex-col justify-between">
                <nav className="flex flex-col p-4">
                    <Link href={'/dashboard'}>
                        <span className='py-2 text-gray-700 hover:text-gray-900'>Hero Card</span>
                    </Link>
                    <Link href={'/dashboard/about'}  className="py-2 text-gray-700 hover:text-gray-900">About</Link>
                    <Link href={'/dashboard/services'}  className="py-2 text-gray-700 hover:text-gray-900">Services</Link>
                    <Link href={'/dashboard/resources'}  className="py-2 text-gray-700 hover:text-gray-900">Resources</Link>
                    <Link href={'/dashboard/testimonials'}  className="py-2 text-gray-700 hover:text-gray-900">Testimonials</Link>
                </nav><div className='p-4'>

                    <Link href={'/'} >
                        <Button text='Home Page'></Button>
                    </Link>
                </div>
            </div>
            {children}
        </div>

    )
}
